### ISSUE TITLE
Conselhos que você daria para um organizador ou uma organizadora de eventos para que os eventos fossem mais inclusivos para pessoas da periferia

### ISSUE THREAD

**Issue by woliveiras** [perifacode/comunidade#1]
Quais conselhos que você daria para um organizador ou uma organizadora de eventos para que os eventos fossem mais inclusivos para pessoas da periferia?

---

Sabemos que para quem é da periferia é muito complicado ir a eventos de programação, como meetups (eventos pequenos/médios mensais) ou conferências (eventos maiores, normalmente anuais).

Eu conheço alguns motivos pelos quais eu não ia nesses eventos e gostaria que você comentasse seu ponto de vista, desse exemplos dos problemas que você enfrenta para ir a eventos de programação.

Estes motivos serão compilados em uma página que ficará em nosso site.

Vamos ajudar os eventos serem mais inclusivos. 🤘 

Para responder você pode colocar algo como:

```
Eu não consigo ir a eventos porque o horário é muito ruim para mim, devido a distância que eu tenho que percorrer.
```

Ou você pode formular uma frase maior. Solte tudo o que tem preso nesse coração aí! 

---

Se você gostou de algum comentário, pode dar um like na conversa clicando no ícone no canto direito da caixa de comentário.

<img width="194" alt="Screen Shot 2019-03-22 at 23 16 05" src="https://user-images.githubusercontent.com/4243601/54860424-8ba5a580-4cf8-11e9-8ceb-168311c1828b.png">

Ou em um joinha que já estiver aqui.

**Comment by woliveiras** [comment]
Eu não ia a meetups porque eles eram sempre depois do expediente de trabalho. Eu demorava 3 horas do meu trabalho até a minha casa, essas 3 horas eram o tempo de duração de um meetup.

**Comment by woliveiras** [comment]
Eu não ia a meetups porque eles sempre aconteciam em São Paulo.

**Comment by woliveiras** [comment]
Eu não ia a meetups porque eles acabam sempre depois das 22 e eu chegaria na minha casa depois das 00:00/00:30 e se eu perdesse o último ônibus não teria como voltar.

**Comment by woliveiras** [comment]
Eu não ia a conferências porque o preço é muito maior do que eu poderia pagar (ingresso em valor absurdo, valor de alimentação e transporte).

**Comment by JhonatanPereira** [comment]
Eu não ia a meetups porque a maior parte deles aconteciam na capital, e ficava inviável pra mim por conta da distância combinada com o horário, pois sempre aconteciam na parte da noite,  tornando complicada para alguém que mora em uma área de risco a volta pra casa

**Comment by giovanisleite** [comment]
Eu não ia a muitos meetups porque a maioria acontecia na zona sul/oeste. Eventos na Paulista já eram bem corridos para voltar para casa (morando em Guarulhos, perto do aeroporto), normalmente, me limitava a ir neles.

Já os eventos pagos, fui em alguns da comunidade Python. O pessoal faz evento de 2~3 dias por R$100 ou menos o ingresso, cheio de gente foda e acessível. Os outros eventos passavam bem longe do orçamento, R$ 300+ para uma trilha de 3 ou 4 palestras é surreal

**Comment by lucasjs** [comment]
Eu não ia para meetups longes para conseguir voltar para casa. Os que eram na mesma região ajudavam, os do centro complicavam, os de outras regiões eram praticamente impossíveis.

Sem contar que eu não ficava para os afters pelo mesmo motivo anterior.

Há alguns que eu não ia justamente por ter um histórico de acabar sempre após o horário estipulado, por exemplo, acabar as 23.

**Comment by rg3915** [comment]
Podemos ver espaços em empresas mais próximas dessas regiões, inclusive faculdades, escolas, etc.

**Comment by carolcodes** [comment]
## Local
- considere fazer eventos afastados dos grandes centros
- cheque se existe transporte coletivo perto do local
- se possível, tenha algo de alimentação, a gente vem do trabalho, cansado e muitas vezes com fome e sem grana para comer algo no caminho, pessoas alimentadas são pessoas mais focadas

## Horário
- eventos na semana a noite costumam ser muito cansativos e difíceis para quem trabalha e mora em região afastada, se mesmo assim optar por realizar, que ele seja curto e/ou acabe cedo
- considere fazer evento aos finais de semana

## Palestrantes
- oriente seu palestrante a preparar um conteúdo inclusivo, conforme falamos na issue #2 ;
- tenha diversidade de pessoas para que os participantes tenham identificação

**Comment by Thomazella** [comment]
divulgacao, preco bom e localizacao viavel

**Comment by angelobelchior** [comment]
Seria interessante tentar fazer parceria nos CEUs. Eles tem uma estrutura muito boa e a maioria fica em regiões periféricas. http://portal.sme.prefeitura.sp.gov.br/Main/Page/PortalSMESP/CEUs--Enderecos

**Comment by LimaIsaias** [comment]
Lembrar do Norte e Nordeste <3

**Comment by niltonslf** [comment]
Eu não ia para meetups porque não haviam eventos já minha cidade. Os que existiam eram em outra cidade e ficava inviável pra ir por conta de transporte.

**Comment by cephalopodluke** [comment]
Não ia a meetups por serem druante a semana e no centro da cidade. Ficava bem fora de mão :/

**Comment by brunagil** [comment]
Eu não ia para meetups porque ficavam muito longe do metrô, que é o meio de transporte mais seguro pra mim. 

Também nunca mais colei num evento que não tinha comida porque era muito foda sair correndo do trabalho, ficar 'presa' no meetup até mais ou menos 22h da noite sem acesso a comida. É algo que para mim precisa ser **avisado** para as pessoas se vai ter ou não, daí podemos nos preparar melhor.

**Comment by juuh42dias** [comment]
Eu não ia para meetups pois na recepção dos prédios o pessoal me pede um documento de identificação e como não tenho meus documentos corrigidos ainda, meu documento de identificação não me representa, isto me gera um desconforto.

Ps: só fazendo esse adendo pra complementar um pouco

**Comment by victormartinez** [comment]
Eu não ia a meetups por faltar uma comunicação mais ampla. Muitas vezes o meetup só é divulgado no Meetup.com e/ou nas listas/grupos do telegram. Para quem ainda não faz parte da comunidade fica difícil saber o que está rolando.

**Comment by btalanski** [comment]
**Organização**
- Optar por divulgar o evento pelo menos 2 semanas antes. Isso dá tempo o suficiente para os interessados  se programarem para comparecer
- Buscar ser o mais inclusivo possível e promover a diversidade.
- Garantir que nenhum tipo de descriminação ocorra antes/durante/depois do evento.
- Data e hora adequada para o publico alvo. Considerar realizar o evento aos finais de semana para atender a maior parte do público.
- Caso o evento seja pago, levar em consideração que nem todos podem pagar por preços altos. 

**Local**
- Optar por locais que tenham fácil acesso através de transporte público
- Caso o evento seja realizado por uma empresa, estudar a possibilidade de oferecer algum tipo comida para os participantes. Alimentos como salgadinhos, sucos e coisas simples são suficientes
- Garantir que o local seja acessível para pessoas com algum tipo de deficiência.
- Garantir que x(s) palestrante(s) tenham acesso ao equipamente necessário para realizar a apresentação da palestra (internet, projetor, etc)

**Palestrante**
- Respeitar a diversidade do publico
- Garantir que o conteúdo seja inclusivo o suficiente para que mesmo o participante mais inexperiente ainda possa obter algum aprendizado sobre o tema em troca do tempo investido em estar lá.
- Compartilhar a apresentação de forma pública com os participantes
- Se dispor a conversar e tirar dúvidas dos participantes antes/durante/depois da apresentação

**Geral**
- Promover o respeito a diversidade
- Promover um ambiente inclusivo e acessível
- Compartilhar conhecimento
-

**Comment by roberson-miguel** [comment]
ter que formar pequenos grupos locais, que possam reunir pelo menos 3 ou 4 pessoas, depois das 9 na sua quebrada, e depois levar esses encontros para um local mais central no fim de semana, dando voz  cada pequeno grupo, para falar suas frustrações e atitudes no desenvolvimento que se espera!
