### ISSUE TITLE
Menções ao fórum

### ISSUE THREAD

**Issue by luisangelorjr** [perifacode/comunidade#15]
Ainda existem menções ao fórum (que inclusive achei nas sugestões do Google, perifaCode Forum)

Estou abrindo pra direcionar o forum.perifacode.com para alguma page e retirar as menções ao fórum no doc

**Comment by gitlherme** [comment]
Nice, mano!

**Comment by rotchajunior** [comment]
Acho que deviamos redirecionar pra raiz do domínio.

**Comment by luisangelorjr** [comment]
Olá amigos:

![image](https://user-images.githubusercontent.com/22268900/74685607-c4225d80-51ad-11ea-8a8b-485929e01d85.png)

**Comment by woliveiras** [comment]
![image](https://user-images.githubusercontent.com/4243601/153714940-d5dea482-c207-4d46-8e4b-d3a97ba70931.png)
