### ISSUE TITLE
Revisar permissões e membros do time - GitHub

### ISSUE THREAD

**Issue by luisangelorjr** [perifacode/comunidade#18]
Necessária a retirada de alguns [membros do time aqui no GitHub](https://github.com/orgs/perifacode/people) e a posterior adição de outros

**Comment by luisangelorjr** [comment]
- [x] Membros ociosos a mais de 6 meses OU oficialmente desligados retirados
- [ ] Adicionar Organizadores ativos como membros do [time](https://github.com/orgs/perifacode/people)

**Comment by woliveiras** [comment]
Done
