### ISSUE TITLE
Link AfroTchBR

### ISSUE THREAD

**Issue by alexandrepd** [perifacode/comunidade#19]
Olá, bom dia!

A conta [AfroTechBR](https://twitter.com/afrotechbr) esta desativada do Twitter.

**Comment by luisangelorjr** [comment]
Opa amigo!
Vim aqui abrir outra issue e acabei de ver a sua

Twitter [isso](https://twitter.com/luisangelorjr/status/1367927216642854916) pra ver onde tão agora

**Comment by luisangelorjr** [comment]
Opa! Feito man.

Vou abrir outra issue pra ver os logos
