### ISSUE TITLE
Conselhos que você daria para palestrantes, para que suas palestras sejam mais inclusivas para pessoas da periferia

### ISSUE THREAD

**Issue by woliveiras** [perifacode/comunidade#2]
Quais conselhos você daria para palestrantes, para que suas palestras sejam mais inclusivas para pessoas da periferia?

Tópico relacionado ao #1.

---

Estes motivos serão compilados em uma página que ficará em nosso site.

Vamos ajudar as palestras a serem mais inclusivas. 🤘 

Para responder você pode colocar algo como:

```
Eu gostaria que os slides fossem xyz...
```

Ou você pode formular uma frase maior. Solte tudo o que tem preso nesse coração aí! 

---

Se você gostou de algum comentário, pode dar um like na conversa clicando no ícone no canto direito da caixa de comentário.

<img width="194" alt="Screen Shot 2019-03-22 at 23 16 05" src="https://user-images.githubusercontent.com/4243601/54860424-8ba5a580-4cf8-11e9-8ceb-168311c1828b.png">

Ou em um joinha que já estiver aqui.

**Comment by woliveiras** [comment]
Nem todo mundo sabe ler inglês. Na periferia temos um cenário pior ainda. Seria bom que os slides de suas palestras fossem em português.

**Comment by woliveiras** [comment]
Não é todo mundo que consegue ter um MacBook, quando você citar algum programa, poderia fazer um paralelo a outro software de plataformas acessíveis (como o Linux ou Windows).

Exemplo: nem todo mundo sabe o que é Homebrew, nem todo mundo usa iTerm2

Se você quiser usar algo alternativo e não conhece, pode procurar no [AlternativeTo](https://alternativeto.net/).

**Comment by woliveiras** [comment]
Nem todo mundo conhece os locais gourmet que você visita, seria bom colocar exemplos acessíveis ao invés de citar visitas ao exterior nos slides de sua palestra.

**Comment by woliveiras** [comment]
Nem todo mundo teve acesso a uma boa educação de base. Seria bom você explicar termos que você acha que todo mundo deveria saber desde o ensino médio, afinal não temos álgebra linear, física quântica ou similares na escola pública (pelo menos na minha não teve).

**Comment by woliveiras** [comment]
Nem todo mundo tem acesso a universidade, por mais que estejamos correndo atrás, seria bom você explicar termos que só são aprendidos lá, pois nós ficamos boiando quando você fala algo que não teria como eu ter aprendido sem a vivência na universidade ou com pessoas que fizeram faculdade.

**Comment by juelisjr** [comment]
Gravar as apresentações com boa qualidade de som e imagem e disponibilizar em alguma plataforma depois (YouTube por exemplo).

**Comment by rccosta** [comment]
Acredito que construir uma didática por slides de forma bem intuitiva, tipo cada slide apresentado que mostre um tempo do código, (mostrar a palavra e sua tradução tipo um glossário da programação. 

Exemplo **function** = _"Isso significa função":_
_Eu acredito que mesmo que seja simples para alguns, ainda assim seria uma maneira fixar a palavra e sua tradução._ 

Uma outra forma seria trabalhar com dialetos ou imagens com humor e pequenos desafios (tipo dinâmicas).

**Comment by lucasjs** [comment]
Ter cores acessíveis para funcionar em qualquer projetor ajudam muito. Muitos talks possuem slides fluorescente, super claros, que quando vão para o projetor não da pra ver nada. Sem contar a fonte minúscula que não dá pra ler nada. Também tem o fato de colocarem um textão em um slide só cujo nem da tempo de ler (e nem é bom ter).

**Comment by rg3915** [comment]
Fundo branco, texto preto ou azul (nada de amarelo) e fonte grande (bem grande).

**Comment by adrianocanofre** [comment]
Cuide para não dizer palavras difíceis . Lembre-se que a palestra está sendo em um local onde muito moradores não tem uma primeiro grau completo.

**Comment by carolcodes** [comment]
## Sobre linguagem:
- evite ao máximo usar termos em inglês, caso seja necessário explique conforme [este](https://github.com/perifacode/comunidade/issues/2#issuecomment-475886745) comentário;
- se possível utilize linguagem neutra e não zombe de vícios de linguagem (como gírias, coisas regionais etc);
- por mais avançado que seja o conteúdo, considere que as pessoas não tem o mesmo histórico que você, por isso, fale como se todos fossem iniciantes.
- cuidado com o discurso da meritocracia, essas coisas não fazem sentido num país extremamente desigual como o nosso;
- fale sobre as possibilidades da tecnologia, não é tudo sobre programar

## Verdades absolutas:
- na periferia a maioria não tem acesso aos melhores computadores, celulares, faculdades, cursos pagos, por isso, não torne essas coisas verdades absolutas ou obrigatórias, ofereça alternativas, SEMPRE;
- não reforce o conto de que programar é fácil, nada é fácil, isso pode gerar frustração no primeiro erro o que pode acarretar em desistência da área;
- não existe linguagem melhor, existem linguagens diferentes para problemas diferentes - não diminua o trabalho alheio;
- MAC ou supercomputadores não são uma realidade para as pessoas na periferia, ensine que todos podem fazer o que vc faz com sistemas diferentes.

## Sobre indicações:
-  no mesmo tópico de linguagem, indique materiais em português e gratuitos;
- considere levar conteúdos de pessoas diversas (pessoas negras, periféricas, LGBTQs);
- se levar conteúdo pago como indicação, que tenha um cupom de desconto considerável ou um preço MUITO em conta.

## Referências:
- sempre que possível, deixe no slide as referências que você usou para produzir aquele conteúdo;
- incentive as pessoas a tirarem foto para guardarem aquele conteúdo para depois;
- poste seu conteúdo em algum lugar além do github ou twitter, pessoas leigas ou iniciantes podem não saber usar essas plataformas;
- deixe seu contato para caso alguém queira pedir ajuda ou até mesmo uma cópia do conteúdo.

**Comment by JosielFaleiros** [comment]
Dar exemplos de coisas simples, legais ou divertidas de preferência fáceis de fazer, ou até mesmo apresentar ferramentas mais simples mas poderosas no sentido do que possibilitam fazer com o mínimo de conhecimento, para que possam começar de fato com as mãos na massa, sem que tenham que passar por uma barreira muito grande que muitas vezes a teoria carrega, pois a geração de valor para a comunidade pode começar com um site feito no Wix, ou um aplicativo feito em alguma plataforma de criação baseada em clicar e arrastar. Demonstrando através de exemplos como essas plataformas podem ser usadas para dar a luz a ideias com o mínimo de conhecimento técnico e recursos.
