### ISSUE TITLE
[C4P] - Hello World com TDD

### ISSUE THREAD

**Issue by azisaka** [perifacode/comunidade#22]
### Descrição da palestra

Hello world com TDD

- Como iniciar um projeto novo a partir de testes
- Como criar um teste para chamar um endpoint de uma API com express
- Como escrever o código para atender os requisitos do teste
- O que fazer depois disso: commit, PR, e aguardar a revisão

Tem bastante tutorial na internet sobre como implementar uma API, mas poucos explicam como testar. Eu gostaria que as pessoas vissem que testes não são um bicho de sete cabeças, e que pudessem ver que é possível fazer TDD sem ser especialista em testes. 

### Nível técnico da palestra

- [x]  Iniciante
- [ ] Intermediário
- [ ] Avançado

### Tipo de palestra

- [ ] Talk/Apresentação - duração de até 25 minutos
- [x] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @azisaka, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário
