### ISSUE TITLE
[C4P] - Roadmap Ciencia de Dados

### ISSUE THREAD

**Issue by andressafreires** [perifacode/comunidade#23]
### Descrição da palestra

Irei falar sobre um roadmap para se tornar cientista de dados. A ideia é que seja uma palestra introdutória para mostrar os benefícios da área e dar dicas do que fazer e estudar para alcançar uma carreira nesse meio -uma vez que a área precisa muito de mais diversidade. Gostaria também de oferecer mentorias gratuitas a todes que quiserem através do meu projeto diversidata.com.br após a palestra. Amo muito o projeto de vocês e seria incrível poder contribuir mais e fazer essa parceria através do meu projeto pra ajudar as pessoas que estarão no evento. Espero que as pessoas saiam da palestra empolgadas e inspiradas.

### Nível técnico da palestra

- [x]  Iniciante
- [ ] Intermediário
- [ ] Avançado

### Tipo de palestra

- [x] Talk/Apresentação - duração de até 25 minutos
- [ ] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @andressafreires, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
