### ISSUE TITLE
[C4P] - Matemática Computacional: que trem é esse?

### ISSUE THREAD

**Issue by thiagonevesuf** [perifacode/comunidade#24]
### Descrição da palestra

- Apresentação: Quem eu sou? De onde venho? Como cheguei aqui? Onde estou? (5m)
- Porquê resolvi estudar matemática computacional? (5m)
- O que é Matemática Computacional? (10m)
- O que faz um Matemático Computacional? (5m)

### Nível técnico da palestra

- [X]  Iniciante
- [ ] Intermediário
- [ ] Avançado

### Tipo de palestra

- [X] Talk/Apresentação - duração de até 25 minutos
- [ ] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @thiagonevesuf, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
