### ISSUE TITLE
[C4P] - Construindo um Portal do Desenvolvedor com Backstage

### ISSUE THREAD

**Issue by danilosoarescardoso** [perifacode/comunidade#25]
### Descrição da palestra

O Backstage é uma ferramenta open source que permite a criação de portais do desenvolvedor, de forma que a criação, gestão do ciclo de vida e descoberta de serviços e APIs seja feito de maneira centralizada e eficiente.  No workshop iremos:

- Criar uma nova instalação do Backstage
- Conhecer as principais funcionalidades
- Instalar um plugin para entender o funcionamento

### Nível técnico da palestra

- [ ]  Iniciante
- [x] Intermediário
- [ ] Avançado

### Tipo de palestra

- [ ] Talk/Apresentação - duração de até 25 minutos
- [x] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @danilosoarescardoso, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
