### ISSUE TITLE
[C4P] - Ainda dá para entrar no mercado de TI ?

### ISSUE THREAD

**Issue by boaglio** [perifacode/comunidade#26]
### Descrição da palestra

Como ninguém nasceu sabendo, sempre existem dúvidas sobre o mercado de TI:
 - É complicado participar?
 - Tem espaço para todos?
 - E quem vem de outra área? Será que é preciso descartar tudo que eu aprendeu em outra área?
 - E como o open-souce pode ajudar em nossa carreira?

Vamos tentar esclarecer essas e outras possíveis dúvidas nessa talk!

### Nível técnico da palestra

- [x]  Iniciante
- [ ] Intermediário
- [ ] Avançado

### Tipo de palestra

- [x] Talk/Apresentação - duração de até 25 minutos
- [ ] Workshop - duração de até 1 hora

### Palestrantes

@boaglio
@dearrudam

**Comment by gitlherme** [comment]
Oi @boaglio, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
