### ISSUE TITLE
[C4P] - Full Stack Vapt Vupt

### ISSUE THREAD

**Issue by eduveks** [perifacode/comunidade#27]
### Descrição da palestra

O que é preciso para ser um desenvolvedor web autónomo para criar as suas próprias soluções completas?

Vou explicar o que é preciso e como é possível dominar minimamente todas as áreas necessárias como Front-end + Back-end + DBA + SA.

Para isto vou demonstrar o que é para mim a melhor receita, quais as tecnologias, que nível de conhecimento mínimo é preciso ter, para finalmente atingir a autonomia.

A partir desta autonomia vai poder encontrar qual é a área que deve especializar-se mais.

Porque acredito que um desenvolvedor web deve ter um entendimento completo de como tudo funciona, se tornar um full stack para depois conseguir descobrir qual é a sua aptidão natural.

É importante encontrar e seguir a sua aptidão natural para conseguir ser um especialista focado na área que tem mais prazer e talento, para isto é preciso conhecer minimamente todo o processo de desenvolvimento web, naturalmente fica capacitado para criar as suas próprias soluções web.

Com tecnologias open source, afinal é o open source que sempre sustentou a web.

Demonstração prática de como desenvolver um sistema web completo e publicar online.

### Nível técnico da palestra

- [x]  Iniciante
- [x] Intermediário
- [x] Avançado

### Tipo de palestra

- [ ] Talk/Apresentação - duração de até 25 minutos
- [x] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @eduveks, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
