### ISSUE TITLE
[C4P] - O que é, desafios e oportunidades na Cloud

### ISSUE THREAD

**Issue by melaniemDev** [perifacode/comunidade#28]
### Descrição da palestra

Hoje vivemos em uma realidade no mercado de tecnologia que quanto mais "**plus**" o profissional ter em seu currículo, mais essa pessoa se destaca. E a Cloud Computing está presente nas empresas de todos os portes, não é mais o futuro, é o agora. Com isso, quero abordar e discutir de forma didática conceitos e oportunidades sobre o tema e o quanto aprender sobre vem ajudado entrar em debates técnicos e tomadas de decisões no meu dia a dia de trabalho.

### Nível técnico da palestra

- [X]  Iniciante
- [ ] Intermediário
- [ ] Avançado

### Tipo de palestra

- [X] Talk/Apresentação - duração de até 25 minutos
- [ ] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Oi @melaniemDev, valeu pelo envio da talk!

Voce pode entrar em contato comigo pelo Discord por favor pra gente combinar certinho?

Guilherme Vieira#5794 é o meu usuário

**Comment by gitlherme** [comment]
Fechando a issue, palestra confirmada para 20/03/2022.
