### ISSUE TITLE
[C4P] - Slack Para Desenvolvedores

### ISSUE THREAD

**Issue by EarthW0rm** [perifacode/comunidade#31]
### Descrição da palestra

A cada dia o slack vem sendo uma ferramenta presente nas áreas de tecnologia, nesse workshop mostro como podemos desenvolver aplicativos complexos no slack.
Além disso vamos falar um pouco sobre o slack enterprise e a uma pincelada sobre a API SCIM do slack disponível no enterprise.

### Nível técnico da palestra

- [X]  Iniciante
- [X] Intermediário
- [X] Avançado

### Tipo de palestra

- [ ] Talk/Apresentação - duração de até 25 minutos
- [X] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
Valeu pela submissão, @EarthW0rm!

Coloquei a label de "In a next event" pois fechamos as submissões pro evento do dia 20, mas entro em contato com vc assim que tiver confirmada a próxima data, tudo bem?

**Comment by gitlherme** [comment]
@EarthW0rm vc pode entrar em contato comigo no Discord pra conversarmos sobre sua talk? Meu usuário é Guilherme Vieira#5794

**Comment by gitlherme** [comment]
Workshop apresentado no dia 16/04/2022.
