### ISSUE TITLE
[C4P] - Principais formas de comunicação entre microsserviços

### ISSUE THREAD

**Issue by vcampitelli** [perifacode/comunidade#33]
### Descrição da palestra

Aprenda as principais maneiras de implementar a comunicação entre microsserviços, como requisições HTTP diretas, serviços de mensageria (utilizando RabbitMQ) e o framework gRPC. Saiba também como implementar os padrões de Sagas e CQRS em cima desses protocolos, além das vantagens e desvantagens de cada um.

### Nível técnico da palestra

- [x] Iniciante
- [x] Intermediário
- [ ] Avançado

### Tipo de palestra

- [ ] Talk/Apresentação - duração de até 25 minutos
- [x] Workshop - duração de até 1 hora

**Comment by gitlherme** [comment]
@vcampitelli valeu por submeter a talk 🙌

Consegue me chamar no Discord pra gente combinar certinho? meu usuário é Guilherme Vieira#5794

**Comment by gitlherme** [comment]
Workshop apresentado no dia 16/04/2022.
