### ISSUE TITLE
Criar ou caçar uma "Awesome List"

### ISSUE THREAD

**Issue by luisangelorjr** [perifacode/comunidade#6]
**Hello, pessoas!**
Acredito que podemos ir alimentando uma lista em pt-br ou até mesmo em inglês de conteúdo gratuito para estudos. Podemos ir traduzindo o material que só tiver em inglês e que tiver viabilidade para trazer para o nosso fluxo e que atinja o maior numero de pessoas efetivamente

Como exemplo, dou essa lista de listas curadas com conteúdo topzera:
https://github.com/sindresorhus/awesome :octocat: 

Ou esse lindo **passo-a-passo do Desenvolvedor Web 2019**:
https://github.com/kamranahmedse/developer-roadmap 🥇 

Ou o meu inseparável app de estudo básico das linguagens, o **SoloLearn**:
https://www.sololearn.com/

Java em pt-br? Tem [Loiane](https://loiane.training/) e [DevDojo](http://devdojo.academy/#/home) total grátis e dão certificado ainda

**Comment by LimaIsaias** [comment]
Esse Repositório aqui tem uma lista de vários Blogs sobre tecnologia em Português, eu acho que também pode ajudar: 
 [https://github.com/Wmitrut/awesome-brazilian-devblogs](https://github.com/Wmitrut/awesome-brazilian-devblogs)

**Comment by luisangelorjr** [comment]
Lembrei de outro:
https://www.cursoemvideo.com/

**Comment by luisangelorjr** [comment]
Opa @juanplopes, tudo bom? Conhece alguma leitura/blog para indicação em pt-br sobre competições?

**Comment by Wmitrut** [comment]
Obrigado @LimaIsaias e pessoal do Perifacode! Assim como @luisangelorjr pelo pull request, a lista está crescendo muito bem e em breve quero organiza-la melhor! Todo PR é bem vindo! Quanto mais ela crescer, mais a gnt pode se beneficiar dela!

**Comment by cephalopodluke** [comment]
Temos também o freecodecamp.org . Hoje ele ainda está em inglês, mas já traduzimos boa parte do site para o português. Conteúdo gratuito e de qualidade =D
