### ISSUE TITLE
Levar a computação para locais com menos acesso 

### ISSUE THREAD

**Issue by woliveiras** [perifacode/comunidade#8]
Durante uma conversa iniciada pelo Reginaldo (QuebraDev), sobre máquinas para a periferia, o Junior (AgendaPreta) trouxe uma ideia legal para nossa comunidade:

> Por que não pegamos máquinas mais antigas, reformamos e utilizamos isso para ensinar programação e/ou doar na periferia?

Visando não perder a comunicação e transformar isso em um projeto do grupo, vamos discutir aqui maneiras de viabilizar essa iniciativa.

Se você tiver qualquer ideia de como podemos fazer para levar computadores para quem não tem condições, comente aqui.

**Comment by yurisbv** [comment]
Duante essa discussão apresentei um desejo meu, um vislumbre, de um curso à baixo custo para jovens periféricxs: o set do computer é um raspberry 3 + teclado + mouse + monitor HDMI ( O mais barato possível ), ao ( final || início ) do curso o aluno ganha o kit.

Com o Raspberry pi é possível programar, com ides leves, em quase todas as linguagem e ainda ser um computador para uso pessoal.

O revendedor oficial https://www.filipeflop.com/ é aberto à parcerias e possivelmente pode ceder um desconto.

**Comment by reginaldojunior** [comment]
@yurisbv 

Acho interresante a proposta do set de computador com rasperry pi. Só que tenho um pequeno problema com isso.

Não é totalmente acessivel por questão de logistica para um pessoa ter que levar ele em eventos e workshop por conta da quantidade de peças.

Fora isso, é totalmente viável a questão do rasperry. Claro, sendo que esse custo seja levantando pelo movimento e pela organização que for da a aula, já que um set desse não deve sair menos que R$ 500.00.

**Comment by alexandre** [comment]
Fiz alguns comentários no telegram, mas o @reginaldojunior  já representou as ideias que eu estava em mente. Acho que o RPi é viavel para quem já tem contato (os exemplos que é possível criar um setup e usar são de entusiastas, por exemplo).
Como fica a autonomia da pessoa em questões mais simples como "está lendo o 'quebrou' algo?"

Acho que nesses casos, mesmo um notebook que não segura muita carga de bateria tem um uso melhor (e pode ser mais fácil de conseguirmos um/alguns). Eu lembro que o Luciano Ramalho chegou a comprar um monitor portatil para usar junto a um RPi e foi bem caro na época...

Um pouco mais longo prazo: como fica a manutenção?

**Comment by reginaldojunior** [comment]
Exatamente @alexandre tem todo isso, acho que o RPi é ótimo, ainda para fazer os jovens se interresar pela programação e em criar coisas, mas quando levamos para questão de logistica, acessibilidade e inclusão não é uma verdade.

**Comment by rotchajunior** [comment]
Salve! Eu gosto do RPi como uma possibilidade, mas ainda acho melhor pensarmos em notebooks doados e/ou de baixo custo pelos seguintes motivos:

- Portabilidade. O estudante pode levar o notebook para qualquer lugar (meetups, encontros, faculdade, cursos, etc.) coisa que, como já disse o @reginaldojunior não é possível com o RPi.
- Arquitetura. O processador do RPi é um arm e nem todos os programas trabalham bem nessa arquitetura. A virtualbox, por exemplo, não rodaria num RPi e isso impossibilitaria de rodar um vagrant ou outro programa que dependa de uma arquitetura de 32 ou 64bits.
- Upgrade. Com um notebook inicialmente simples, o estudante pode ir fazendo pequenos upgrades que podem prolongar e otimizar o uso do equipamento. Por exemplo, hoje em dia os SSDs tem ficado bem mais baratos e eles podem melhorar em muito a performance de um sistema. Notebooks também possibilitam o upgrade de memoria RAM, coisa que não é possível no RPi.

Um outro ponto que julgo interessante é fazermos oficinas de recuperação de maquinas com os equipamentos que nos forem doados. Acredito que isso dá uma independência grande para as pessoas, pois dominando algumas técnicas de manutenção elas podem por si só cuidar de seu próprio hardware e, além disso, também oferecer esse tipo de serviço caso seja de interesse.

**Comment by hudymoreira** [comment]
Olá jovens tudo bem? meu cordial boa tarde, me chamo Hudson e sou do Embu das Artes,  moro no Jd Casa Branca e la consegui construir uma escolinha de informática onde ensino programação de graça para quem estiver interessado. Ultimamente muitos jovens da ETEC do Embu tem frequentado os cursos [Sala](https://github.com/hudymoreira/cursoPHP/blob/master/fotos/sala.jpg)
tudo que os alunos desenvolvem disponibilizo aqui no git, e no fim de cada curso entrego um certificado aos alunos [turma1](https://github.com/hudymoreira/cursoPHP/blob/master/fotos/turma1.jpg) [turma2](https://github.com/hudymoreira/cursoPHP/blob/master/fotos/turma2.jpg)
minha primeira escolinha foi na favela do inferninho na biblioteca  [Zumaluma](http://photos1.blogger.com/blogger/2710/2148/1600/informatica%20scanner.jpg)
mas os traficantes espirraram a gente de lá porque eles não queriam gente de fora circulando na quebrada rsrs 
Desde a quela época eu usava o [LTSP](http://www.ltsp.org) onde eu pegava sucata de computadores sem HD com pouca memória e dividia um computador bom em até 10 terminais
saindo da zumaluma eu consegui por um telecentro com essa tecnologia de computadores reciclados em todas as bibliotecas de embu  em 2012 [detalhes aqui](http://cidadeembudasartes.sp.gov.br/embu/portal/noticia/ver/4769) funcionou muito bem por bastante tempo, dai eu precisei estudar e trabalhar... e hj eu dedico meus fins de semana à atividades na escolinha, la eu ensino de tudo um pouco, como :

- Programação ( PHP,Python,JavaScript,java );

- Desenvolvimento de Aplicativos (Ionic cordova);

- Desenvolvimento de sites (Angular);

- Impressão 3d ( [feita com sucata](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10208532732354383/?type=3), [impressora normal](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10208972225901447/?type=3)  )
- games com Raspberry Pi ( [game1](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10205299825013720/?type=3), [game2](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10208132111459111/?type=3) )

- game com raspberry e impressora 3d [piboy](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10210727577944151/?type=3)

- arduino ( [malaquias](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10208480251042383/?type=3) )

- computadores antigos [Macintish](https://www.facebook.com/hudson.moreiraguimaraes/videos/vb.1790445944/10210855275496510/?type=3) 
Essas são umas das coisas que sei fazer, infelizmente dependendo do curso vc realmente precisa de um computador bom, hj em dia a vibe é fazer app e por dados na nuvem, felizmente é possível fazer isso computadores não tão bons kkk o primeiro curso que dei de android foi em maquinas de sucata e os alunos conseguiram fazer um app de [gerenciamento de vendas de pasteis](https://play.google.com/store/apps/details?id=br.com.wecare.www.pastelaria), o app foi baixado em 9 países diferentes, bom, sempre fui a favor do reaproveitamento de tecnologias,  essas referencias mostram um pouco da minha experiencia nesse assunto... se eu poder ajudar com alguma coisa nesse sentido, estou a ai pra gente bolar unas ideias...  
bom saber também que tem mais pessoas nessa mesma pegada... satisfação em conhece-los.

**Comment by luisangelorjr** [comment]
Opa @hudymoreira!
Que show mano!

Já está no nosso telegram? Comentaram a pouco do seu post comment aqui.

Bora lá?

**Comment by hudymoreira** [comment]
fala jovem @luisangelorjr  quebrei meu telefone, não tenho esse  telegram mas posso instalar

**Comment by yurisbv** [comment]
> Salve! Eu gosto do RPi como uma possibilidade, mas ainda acho melhor pensarmos em notebooks doados e/ou de baixo custo pelos seguintes motivos:
> 
>     * Portabilidade. O estudante pode levar o notebook para qualquer lugar (meetups, encontros, faculdade, cursos, etc.) coisa que, como já disse o @reginaldojunior não é possível com o RPi.
> 
>     * Arquitetura. O processador do RPi é um arm e nem todos os programas trabalham bem nessa arquitetura. A virtualbox, por exemplo, não rodaria num RPi e isso impossibilitaria de rodar um vagrant ou outro programa que dependa de uma arquitetura de 32 ou 64bits.
> 
>     * Upgrade. Com um notebook inicialmente simples, o estudante pode ir fazendo pequenos upgrades que podem prolongar e otimizar o uso do equipamento. Por exemplo, hoje em dia os SSDs tem ficado bem mais baratos e eles podem melhorar em muito a performance de um sistema. Notebooks também possibilitam o upgrade de memoria RAM, coisa que não é possível no RPi.
> 
> 
> Um outro ponto que julgo interessante é fazermos oficinas de recuperação de maquinas com os equipamentos que nos forem doados. Acredito que isso dá uma independência grande para as pessoas, pois dominando algumas técnicas de manutenção elas podem por si só cuidar de seu próprio hardware e, além disso, também oferecer esse tipo de serviço caso seja de interesse.

Você tem toda razão, o notebook é bem mais útil que o RPI

**Comment by luisangelorjr** [comment]
@hudymoreira tenta ae man. 
Se não der, podemos ir conversando por aqui ou criar algo no fórum https://forum.perifacode.com/

**Comment by luisangelorjr** [comment]
@hudymoreira opa man! Tem algum e-mail ou contato que podemos ir trocando ideia, ou por aqui mesmo?

**Comment by hudymoreira** [comment]
@luisangelorjr te mandei meu zap, to na correria pq troque de trampo, tem dois dias e eu to quebrando a cabeçar com código legado... mas to de boa nos fins de semana
