### ISSUE TITLE
Nordeste Digital

### ISSUE THREAD

**Issue by uira** [perifacode/comunidade#9]
Estou aqui na periferia de Fortaleza tocando alguns projetos na área.

**Comment by luisangelorjr** [comment]
Opa man!
Tenho interesse. Conta mais o que está fazendo e o que podemos tentar ajudar daqui 👍

**Comment by luisangelorjr** [comment]
@uira  eae man! Ta por aí?

**Comment by uira** [comment]
Eu tava naquelas de querer terminar antes de mandar o link, mas como demorou, vai o Work In Progress mesmo... 

Tem esse: https://github.com/Mutirao/EditalDeRedes/issues/1

e tem esse: https://github.com/redelivre/Governanca

tipo isso... ;)

**Comment by LimaIsaias** [comment]
Sou de fortaleza também, tô vendo o repositório que vc linkou e tá legal, queria poder ajudar mas não codo em php nem conheço wordpress, tem alguma forma de colaborar ?

**Comment by uira** [comment]
me passa seu telegram e bora combinar um encontro na Casa da Cultura
Digital.

o meu é t.me/uirapora
